### ISSUE TITLE
not compatible with Kotlin 1.3

### ISSUE THREAD

**Issue by luvcraft** [Appnroll/box-android#1]
When I try to build this project, it tells me that the Kotlin version is outdated.

After updating `ext.kotlin_version` to `1.3.20` in `build.gradle`, it will build, but when I run it, nothing appears for “cat WEBP” or “cat GIF”, unless I check “Use BitmapFactory”, in which case only the first frame appears. The jpegs appear correctly, however.

Android Studio also complains about the use of "experimental" `kotlinx.coroutines` imports.

**Comment by ghost** [comment]
Hi, I've updated Kotlin version. You can try it now. If stil nothing appears for “cat WEBP” or “cat GIF” please send me the details of the device you have tested it and also check if there are no exceptions in the logcat

**Comment by luvcraft** [comment]
that did the trick! thank you so much!! 👍
